-- Migration for table: bumdes
-- Generated: 2025-11-10T06:26:42.572Z

CREATE TABLE `bumdes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `desa_id` bigint unsigned DEFAULT NULL,
  `kode_desa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kecamatan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `desa` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `namabumdesa` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'aktif',
  `keterangan_tidak_aktif` text COLLATE utf8mb4_unicode_ci,
  `NIB` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LKPP` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NPWP` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `badanhukum` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NamaPenasihat` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisKelaminPenasihat` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HPPenasihat` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NamaPengawas` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisKelaminPengawas` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HPPengawas` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NamaDirektur` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisKelaminDirektur` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HPDirektur` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NamaSekretaris` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisKelaminSekretaris` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HPSekretaris` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NamaBendahara` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisKelaminBendahara` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HPBendahara` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TahunPendirian` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AlamatBumdesa` text COLLATE utf8mb4_unicode_ci,
  `Alamatemail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TotalTenagaKerja` int DEFAULT NULL,
  `TelfonBumdes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisUsaha` text COLLATE utf8mb4_unicode_ci,
  `JenisUsahaUtama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JenisUsahaLainnya` text COLLATE utf8mb4_unicode_ci,
  `Omset2023` decimal(15,2) DEFAULT NULL,
  `Laba2023` decimal(15,2) DEFAULT NULL,
  `Omset2024` decimal(15,2) DEFAULT NULL,
  `Laba2024` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2019` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2020` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2021` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2022` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2023` decimal(15,2) DEFAULT NULL,
  `PenyertaanModal2024` decimal(15,2) DEFAULT NULL,
  `SumberLain` decimal(15,2) DEFAULT NULL,
  `JenisAset` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NilaiAset` decimal(15,2) DEFAULT NULL,
  `KerjasamaPihakKetiga` text COLLATE utf8mb4_unicode_ci,
  `TahunMulai-TahunBerakhir` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KontribusiTerhadapPADes2021` decimal(15,2) DEFAULT NULL,
  `KontribusiTerhadapPADes2022` decimal(15,2) DEFAULT NULL,
  `KontribusiTerhadapPADes2023` decimal(15,2) DEFAULT NULL,
  `KontribusiTerhadapPADes2024` decimal(15,2) DEFAULT NULL,
  `Ketapang2024` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Ketapang2025` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BantuanKementrian` text COLLATE utf8mb4_unicode_ci,
  `BantuanLaptopShopee` text COLLATE utf8mb4_unicode_ci,
  `NomorPerdes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DesaWisata` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LaporanKeuangan2021` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LaporanKeuangan2022` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LaporanKeuangan2023` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LaporanKeuangan2024` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Perdes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `produk_hukum_perdes_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ProfilBUMDesa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BeritaAcara` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AnggaranDasar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AnggaranRumahTangga` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ProgramKerja` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SK_BUM_Desa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `produk_hukum_sk_bumdes_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bumdes_kode_desa_unique` (`kode_desa`),
  KEY `bumdes_desa_id_foreign` (`desa_id`),
  KEY `bumdes_produk_hukum_perdes_id_foreign` (`produk_hukum_perdes_id`),
  KEY `bumdes_produk_hukum_sk_bumdes_id_foreign` (`produk_hukum_sk_bumdes_id`),
  CONSTRAINT `bumdes_desa_id_foreign` FOREIGN KEY (`desa_id`) REFERENCES `desas` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bumdes_produk_hukum_perdes_id_foreign` FOREIGN KEY (`produk_hukum_perdes_id`) REFERENCES `produk_hukums` (`id`) ON DELETE SET NULL,
  CONSTRAINT `bumdes_produk_hukum_sk_bumdes_id_foreign` FOREIGN KEY (`produk_hukum_sk_bumdes_id`) REFERENCES `produk_hukums` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=214 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
