-- Migration: Create bankeu_surat_templates table
-- Date: 2026-02-18
-- Description: Stores editable surat template formats for bankeu module

CREATE TABLE IF NOT EXISTS `bankeu_surat_templates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kode` VARCHAR(50) NOT NULL COMMENT 'Unique template code: surat_pengantar, surat_permohonan, etc.',
  `nama` VARCHAR(255) NOT NULL COMMENT 'Display name of the template',
  `deskripsi` TEXT NULL COMMENT 'Description/purpose of this template',
  `kategori` ENUM('desa', 'kecamatan') NOT NULL DEFAULT 'desa' COMMENT 'Which level uses this template',
  `content_html` LONGTEXT NOT NULL COMMENT 'HTML template content with placeholders like {{nama_desa}}, {{tahun_anggaran}}',
  `placeholders` JSON NULL COMMENT 'JSON array of available placeholders with descriptions',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `updated_by_user_id` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_kode` (`kode`),
  KEY `idx_kategori` (`kategori`),
  KEY `fk_surat_template_user` (`updated_by_user_id`),
  CONSTRAINT `fk_surat_template_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed default templates
INSERT INTO `bankeu_surat_templates` (`kode`, `nama`, `deskripsi`, `kategori`, `content_html`, `placeholders`) VALUES
(
  'surat_pengantar_desa',
  'Surat Pengantar Desa',
  'Template surat pengantar yang digunakan desa untuk mengajukan proposal bantuan keuangan',
  'desa',
  '<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">\n  <div style="text-align: center; border-bottom: 3px double #000; padding-bottom: 15px; margin-bottom: 20px;">\n    <h3 style="margin: 0;">PEMERINTAH KABUPATEN BOGOR</h3>\n    <h2 style="margin: 5px 0;">KECAMATAN {{nama_kecamatan}}</h2>\n    <h3 style="margin: 5px 0;">DESA {{nama_desa}}</h3>\n    <p style="font-size: 12px; margin: 5px 0;">{{alamat_desa}}</p>\n  </div>\n\n  <div style="text-align: right; margin-bottom: 20px;">\n    <p>{{nama_desa}}, {{tanggal_surat}}</p>\n  </div>\n\n  <table style="margin-bottom: 15px;">\n    <tr><td style="width: 80px;">Nomor</td><td>: {{nomor_surat}}</td></tr>\n    <tr><td>Lampiran</td><td>: {{lampiran}}</td></tr>\n    <tr><td>Perihal</td><td>: <strong>Pengantar Proposal Bantuan Keuangan TA {{tahun_anggaran}}</strong></td></tr>\n  </table>\n\n  <div style="margin-bottom: 20px;">\n    <p>Kepada Yth.</p>\n    <p><strong>Bupati Bogor</strong></p>\n    <p>Melalui Kepala DPMD Kabupaten Bogor</p>\n    <p>Di - Cibinong</p>\n  </div>\n\n  <div style="margin-bottom: 20px;">\n    <p>Dengan hormat,</p>\n    <p style="text-align: justify;">Bersama ini kami sampaikan Proposal Permohonan Bantuan Keuangan Khusus Akselerasi Pembangunan Perdesaan Tahun Anggaran {{tahun_anggaran}} dari Desa {{nama_desa}} Kecamatan {{nama_kecamatan}} Kabupaten Bogor untuk dapat diproses lebih lanjut.</p>\n    <p style="text-align: justify;">Demikian surat pengantar ini kami sampaikan, atas perhatian dan kerjasamanya kami ucapkan terima kasih.</p>\n  </div>\n\n  <div style="text-align: right; margin-top: 40px;">\n    <p>Kepala Desa {{nama_desa}}</p>\n    <br/><br/><br/>\n    <p><strong><u>{{nama_kepala_desa}}</u></strong></p>\n  </div>\n</div>',
  '[{"key": "nama_desa", "label": "Nama Desa", "contoh": "Sukamaju"}, {"key": "nama_kecamatan", "label": "Nama Kecamatan", "contoh": "Cibinong"}, {"key": "alamat_desa", "label": "Alamat Desa", "contoh": "Jl. Raya Sukamaju No. 1"}, {"key": "tanggal_surat", "label": "Tanggal Surat", "contoh": "18 Februari 2026"}, {"key": "nomor_surat", "label": "Nomor Surat", "contoh": "001/DS/II/2026"}, {"key": "lampiran", "label": "Lampiran", "contoh": "1 (satu) berkas"}, {"key": "tahun_anggaran", "label": "Tahun Anggaran", "contoh": "2026"}, {"key": "nama_kepala_desa", "label": "Nama Kepala Desa", "contoh": "H. Ahmad Sudirman"}]'
),
(
  'surat_permohonan_desa',
  'Surat Permohonan Desa',
  'Template surat permohonan bantuan keuangan yang diajukan oleh desa',
  'desa',
  '<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">\n  <div style="text-align: center; border-bottom: 3px double #000; padding-bottom: 15px; margin-bottom: 20px;">\n    <h3 style="margin: 0;">PEMERINTAH KABUPATEN BOGOR</h3>\n    <h2 style="margin: 5px 0;">KECAMATAN {{nama_kecamatan}}</h2>\n    <h3 style="margin: 5px 0;">DESA {{nama_desa}}</h3>\n    <p style="font-size: 12px; margin: 5px 0;">{{alamat_desa}}</p>\n  </div>\n\n  <div style="text-align: right; margin-bottom: 20px;">\n    <p>{{nama_desa}}, {{tanggal_surat}}</p>\n  </div>\n\n  <table style="margin-bottom: 15px;">\n    <tr><td style="width: 80px;">Nomor</td><td>: {{nomor_surat}}</td></tr>\n    <tr><td>Lampiran</td><td>: {{lampiran}}</td></tr>\n    <tr><td>Perihal</td><td>: <strong>Permohonan Bantuan Keuangan Khusus TA {{tahun_anggaran}}</strong></td></tr>\n  </table>\n\n  <div style="margin-bottom: 20px;">\n    <p>Kepada Yth.</p>\n    <p><strong>Bupati Bogor</strong></p>\n    <p>Melalui Kepala DPMD Kabupaten Bogor</p>\n    <p>Di - Cibinong</p>\n  </div>\n\n  <div style="margin-bottom: 20px;">\n    <p>Dengan hormat,</p>\n    <p style="text-align: justify;">Yang bertanda tangan di bawah ini, Kepala Desa {{nama_desa}} Kecamatan {{nama_kecamatan}} Kabupaten Bogor, dengan ini mengajukan permohonan Bantuan Keuangan Khusus Akselerasi Pembangunan Perdesaan Tahun Anggaran {{tahun_anggaran}} dengan rincian sebagai berikut:</p>\n  </div>\n\n  <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">\n    <thead>\n      <tr>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">No</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Nama Kegiatan</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Volume</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Lokasi</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Anggaran (Rp)</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td style="border: 1px solid #000; padding: 8px; text-align: center;">{{nomor_urut}}</td>\n        <td style="border: 1px solid #000; padding: 8px;">{{nama_kegiatan}}</td>\n        <td style="border: 1px solid #000; padding: 8px; text-align: center;">{{volume}}</td>\n        <td style="border: 1px solid #000; padding: 8px;">{{lokasi}}</td>\n        <td style="border: 1px solid #000; padding: 8px; text-align: right;">{{anggaran}}</td>\n      </tr>\n    </tbody>\n  </table>\n\n  <div style="margin-bottom: 20px;">\n    <p style="text-align: justify;">Demikian surat permohonan ini kami sampaikan dengan harapan dapat dikabulkan. Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>\n  </div>\n\n  <div style="text-align: right; margin-top: 40px;">\n    <p>Kepala Desa {{nama_desa}}</p>\n    <br/><br/><br/>\n    <p><strong><u>{{nama_kepala_desa}}</u></strong></p>\n  </div>\n</div>',
  '[{"key": "nama_desa", "label": "Nama Desa", "contoh": "Sukamaju"}, {"key": "nama_kecamatan", "label": "Nama Kecamatan", "contoh": "Cibinong"}, {"key": "alamat_desa", "label": "Alamat Desa", "contoh": "Jl. Raya Sukamaju No. 1"}, {"key": "tanggal_surat", "label": "Tanggal Surat", "contoh": "18 Februari 2026"}, {"key": "nomor_surat", "label": "Nomor Surat", "contoh": "001/DS/II/2026"}, {"key": "lampiran", "label": "Lampiran", "contoh": "1 (satu) berkas"}, {"key": "tahun_anggaran", "label": "Tahun Anggaran", "contoh": "2026"}, {"key": "nama_kegiatan", "label": "Nama Kegiatan", "contoh": "Pembangunan Jalan Desa"}, {"key": "volume", "label": "Volume", "contoh": "500 m"}, {"key": "lokasi", "label": "Lokasi", "contoh": "RT 01/RW 02"}, {"key": "anggaran", "label": "Anggaran", "contoh": "500.000.000"}, {"key": "nomor_urut", "label": "Nomor Urut", "contoh": "1"}, {"key": "nama_kepala_desa", "label": "Nama Kepala Desa", "contoh": "H. Ahmad Sudirman"}]'
),
(
  'surat_pengantar_kecamatan',
  'Surat Pengantar Kecamatan',
  'Template surat pengantar dari kecamatan untuk meneruskan proposal ke DPMD',
  'kecamatan',
  '<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">\n  <div style="text-align: center; border-bottom: 3px double #000; padding-bottom: 15px; margin-bottom: 20px;">\n    <h3 style="margin: 0;">PEMERINTAH KABUPATEN BOGOR</h3>\n    <h2 style="margin: 5px 0;">KECAMATAN {{nama_kecamatan}}</h2>\n    <p style="font-size: 12px; margin: 5px 0;">{{alamat_kecamatan}} Kode Pos {{kode_pos}}</p>\n    <p style="font-size: 12px; margin: 2px 0; font-style: italic;">Telp. {{telepon}} | {{website}} | {{email}}</p>\n  </div>\n\n  <div style="text-align: right; margin-bottom: 20px;">\n    <p>{{nama_kecamatan}}, {{tanggal_surat}}</p>\n  </div>\n\n  <table style="margin-bottom: 15px;">\n    <tr><td style="width: 80px;">Kepada</td><td>:</td></tr>\n    <tr><td></td><td>Yth. <strong>BUPATI BOGOR</strong></td></tr>\n    <tr><td></td><td>Melalui Kepala DPMD Kabupaten Bogor</td></tr>\n    <tr><td></td><td>Di - Cibinong</td></tr>\n  </table>\n\n  <div style="text-align: center; margin: 30px 0;">\n    <h3 style="text-decoration: underline;">SURAT PENGANTAR</h3>\n    <p>Nomor : {{nomor_surat}}</p>\n  </div>\n\n  <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">\n    <thead>\n      <tr>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">No</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Jenis yang dikirim</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Banyaknya</th>\n        <th style="border: 1px solid #000; padding: 8px; text-align: center;">Keterangan</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td style="border: 1px solid #000; padding: 8px; text-align: center;">1.</td>\n        <td style="border: 1px solid #000; padding: 8px;">Proposal Permohonan Bantuan Keuangan Khusus Akselerasi Pembangunan Perdesaan Tahun Anggaran {{tahun_anggaran}}<br/>Desa {{nama_desa}}</td>\n        <td style="border: 1px solid #000; padding: 8px; text-align: center;">1 (satu) berkas</td>\n        <td style="border: 1px solid #000; padding: 8px;"></td>\n      </tr>\n    </tbody>\n  </table>\n\n  <p style="margin-bottom: 30px;">Diterima pada tanggal : ............................</p>\n\n  <div style="display: flex; justify-content: space-between; margin-top: 20px;">\n    <div style="text-align: center; width: 45%;">\n      <p>Penerima</p>\n      <br/><br/><br/>\n      <p>( ...................................... )</p>\n    </div>\n    <div style="text-align: center; width: 45%;">\n      <p><strong>CAMAT,</strong></p>\n      <br/><br/><br/>\n      <p><strong><u>{{nama_camat}}</u></strong></p>\n      <p>NIP. {{nip_camat}}</p>\n    </div>\n  </div>\n</div>',
  '[{"key": "nama_kecamatan", "label": "Nama Kecamatan", "contoh": "Cibinong"}, {"key": "alamat_kecamatan", "label": "Alamat Kecamatan", "contoh": "Jl. Raya Cibinong No. 1"}, {"key": "kode_pos", "label": "Kode Pos", "contoh": "16911"}, {"key": "telepon", "label": "Telepon", "contoh": "(021) 8752xxx"}, {"key": "website", "label": "Website", "contoh": "www.kecamatancibinong.bogorkab.go.id"}, {"key": "email", "label": "Email", "contoh": "kec.cibinong@bogorkab.go.id"}, {"key": "tanggal_surat", "label": "Tanggal Surat", "contoh": "18 Februari 2026"}, {"key": "nomor_surat", "label": "Nomor Surat", "contoh": "005/Kec/II/2026"}, {"key": "tahun_anggaran", "label": "Tahun Anggaran", "contoh": "2026"}, {"key": "nama_desa", "label": "Nama Desa", "contoh": "Sukamaju"}, {"key": "nama_camat", "label": "Nama Camat", "contoh": "Drs. H. Ahmad"}, {"key": "nip_camat", "label": "NIP Camat", "contoh": "19700101 199903 1 001"}]'
);
